### ISSUE TITLE
Error in commit references unknown v${version}.tar.gz

### ISSUE THREAD

**Issue by mwbringmann** [power-ras/ppc64-diag#1]
Error in commit 02bc47031a260739d7e12aa65ad4936ed96427fa produces the following error message for rpmbuild:

[root@RHEL8 ppc64-diag]# rpmbuild -ba ~/rpmbuild/SPECS/ppc64-diag.spec
error: Bad source: /root/rpmbuild/SOURCES/v2.7.6.tar.gz: No such file or directory
[root@RHEL8 ppc64-diag]#

The commit includes the change,

-Source0: https://github.com/power-ras/ppc64-diag.git
+Source0: https://github.com/power-ras/%{name}/archive/v%{version}.tar.gz

which should have been,

-Source0: https://github.com/power-ras/ppc64-diag.git
+Source0: https://github.com/power-ras/%{name}/archive/ppc64-diag-%{version}.tar.gz

to match the file generated by the 'make dist-gzip' operation.

**Comment by hegdevasant** [comment]
Thanks for the report. I will fix it next week.

-Vasant
